FROM python:3.7-slim
RUN sed -i "s@http://deb.debian.org/debian@http://10.110.63.27/repository/debian-proxy@g" /etc/apt/sources.list \
  && sed -i "s@http://security.debian.org/debian-security@http://10.110.63.27/repository/debian-security@g" /etc/apt/sources.list

MAINTAINER zhuhd  zhuhaodong@inspur.com
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    libxrender1 \
    libglib2.0-bin \
    libgomp1 \
    libgl1-mesa-glx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

RUN python3 -m pip install --upgrade --no-cache-dir -i https://pypi.doubanio.com/simple/ \
    opencv-python \
    matplotlib \  
    uvicorn \
    fastapi \
    pillow \
    requests \
    scipy \
    scikit-image

RUN python3 -m pip install --upgrade --no-cache-dir -i https://pypi.doubanio.com/simple/ \
    torch==1.6.0\
    torchvision==0.7.0

RUN python3 -m pip install --upgrade --no-cache-dir -i https://pypi.doubanio.com/simple/ \
    pyyaml \
    tqdm \
    kazoo \
    minio \
    redis \
    pika \
    aiofiles

ENV USE_GPU false

COPY . /project

WORKDIR /project

RUN cp /project/requests/protobuf/protoc_x86_64 /usr/bin/protoc                          \
    && cd /project/requests/protobuf/protobuf-3.18.0/python && python3 setup.py install  \
    && rm -rf /project/requests

RUN python3 -m compileall -b . \
    && find -name "*.py" | xargs rm -rf \
    && find -name "__pycache__" | xargs rm -rf

EXPOSE 8018
CMD ["python3","/project/src/main.pyc"]
