# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63onsumer.proto\"\xe9\x02\n\ttask_info\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.task_info.image_type\x12$\n\x05image\x18\x03 \x03(\x0b\x32\x15.task_info.image_info\x12$\n\x05param\x18\x04 \x03(\x0b\x32\x15.task_info.param_info\x12\r\n\x05\x65xtra\x18\x05 \x01(\t\x1a^\n\nimage_info\x12\x0f\n\x07imageId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x12\n\nchannelNum\x18\x05 \x01(\x05\x1a(\n\nparam_info\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"B\n\nimage_type\x12\x08\n\x04None\x10\x00\x12\n\n\x06\x42INARY\x10\x01\x12\t\n\x05\x42GR24\x10\x02\x12\x07\n\x03URL\x10\x03\x12\n\n\x06\x42\x41SE64\x10\x04\x62\x06proto3')
)



_TASK_INFO_IMAGE_TYPE = _descriptor.EnumDescriptor(
  name='image_type',
  full_name='task_info.image_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINARY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR24', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE64', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=314,
  serialized_end=380,
)
_sym_db.RegisterEnumDescriptor(_TASK_INFO_IMAGE_TYPE)


_TASK_INFO_IMAGE_INFO = _descriptor.Descriptor(
  name='image_info',
  full_name='task_info.image_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='task_info.image_info.imageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='task_info.image_info.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='task_info.image_info.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='task_info.image_info.width', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelNum', full_name='task_info.image_info.channelNum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=270,
)

_TASK_INFO_PARAM_INFO = _descriptor.Descriptor(
  name='param_info',
  full_name='task_info.param_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='task_info.param_info.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='task_info.param_info.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=312,
)

_TASK_INFO = _descriptor.Descriptor(
  name='task_info',
  full_name='task_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='task_info.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='task_info.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='task_info.image', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='task_info.param', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='task_info.extra', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TASK_INFO_IMAGE_INFO, _TASK_INFO_PARAM_INFO, ],
  enum_types=[
    _TASK_INFO_IMAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=380,
)

_TASK_INFO_IMAGE_INFO.containing_type = _TASK_INFO
_TASK_INFO_PARAM_INFO.containing_type = _TASK_INFO
_TASK_INFO.fields_by_name['type'].enum_type = _TASK_INFO_IMAGE_TYPE
_TASK_INFO.fields_by_name['image'].message_type = _TASK_INFO_IMAGE_INFO
_TASK_INFO.fields_by_name['param'].message_type = _TASK_INFO_PARAM_INFO
_TASK_INFO_IMAGE_TYPE.containing_type = _TASK_INFO
DESCRIPTOR.message_types_by_name['task_info'] = _TASK_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

task_info = _reflection.GeneratedProtocolMessageType('task_info', (_message.Message,), {

  'image_info' : _reflection.GeneratedProtocolMessageType('image_info', (_message.Message,), {
    'DESCRIPTOR' : _TASK_INFO_IMAGE_INFO,
    '__module__' : 'consumer_pb2'
    # @@protoc_insertion_point(class_scope:task_info.image_info)
    })
  ,

  'param_info' : _reflection.GeneratedProtocolMessageType('param_info', (_message.Message,), {
    'DESCRIPTOR' : _TASK_INFO_PARAM_INFO,
    '__module__' : 'consumer_pb2'
    # @@protoc_insertion_point(class_scope:task_info.param_info)
    })
  ,
  'DESCRIPTOR' : _TASK_INFO,
  '__module__' : 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:task_info)
  })
_sym_db.RegisterMessage(task_info)
_sym_db.RegisterMessage(task_info.image_info)
_sym_db.RegisterMessage(task_info.param_info)


# @@protoc_insertion_point(module_scope)
